-- Active: 1758640196548@@127.0.0.1@5432@flash_sale_api
@host = http://127.0.0.1:8000
@contentType = application/json

### Get Product
# @name getProduct
GET {{host}}/api/products/1
Accept: {{contentType}}

### Create Order
# @name createOrder
POST {{host}}/api/orders
Content-Type: {{contentType}}
Accept: {{contentType}}

{
    "product_id": "{{getProduct.response.body.id}}",
    "qty": 10
}

### Payment Webhook (Success)
POST {{host}}/api/payments/webhook
Content-Type: {{contentType}}
Accept: {{contentType}}

{
    "order_reference": "{{createOrder.response.body.order_reference}}",
    "status": "success"
}

### Payment Webhook (Failure)
POST {{host}}/api/payments/webhook
Content-Type: {{contentType}}
Accept: {{contentType}}

{
    "order_reference": "{{createOrder.response.body.order_reference}}",
    "status": "failure"
}
